CREATE TYPE "public"."forum_status" AS ENUM('OPEN', 'CLOSED', 'ARCHIVED');--> statement-breakpoint
CREATE TABLE "gonzaapp_forum_response" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gonzaapp_forum_response_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"forumId" integer,
	"content" text NOT NULL,
	"responderId" varchar(256) NOT NULL,
	"upvotes" integer DEFAULT 0,
	"downvotes" integer DEFAULT 0,
	"parentId" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "gonzaapp_forum" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gonzaapp_forum_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer,
	"title" varchar(256) NOT NULL,
	"question" text NOT NULL,
	"creatorId" varchar(256) NOT NULL,
	"status" "forum_status" DEFAULT 'OPEN' NOT NULL,
	"upvotes" integer DEFAULT 0,
	"downvotes" integer DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "gonzaapp_forum_response" ADD CONSTRAINT "gonzaapp_forum_response_forumId_gonzaapp_forum_id_fk" FOREIGN KEY ("forumId") REFERENCES "public"."gonzaapp_forum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gonzaapp_forum_response" ADD CONSTRAINT "gonzaapp_forum_response_parentId_gonzaapp_forum_response_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."gonzaapp_forum_response"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gonzaapp_forum" ADD CONSTRAINT "gonzaapp_forum_eventId_gonzaapp_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."gonzaapp_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "response_forum_idx" ON "gonzaapp_forum_response" USING btree ("forumId");--> statement-breakpoint
CREATE INDEX "response_responder_idx" ON "gonzaapp_forum_response" USING btree ("responderId");--> statement-breakpoint
CREATE INDEX "response_parent_idx" ON "gonzaapp_forum_response" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "forum_event_idx" ON "gonzaapp_forum" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "forum_creator_idx" ON "gonzaapp_forum" USING btree ("creatorId");--> statement-breakpoint
CREATE INDEX "forum_status_idx" ON "gonzaapp_forum" USING btree ("status");