CREATE TYPE "public"."action_type" AS ENUM('COLLECT', 'DONATE', 'PARTICIPATE', 'SHARE', 'OTHER');--> statement-breakpoint
CREATE TABLE "event_evidence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_evidence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer,
	"participantId" varchar(256) NOT NULL,
	"imageUrl" varchar(512) NOT NULL,
	"description" text,
	"verified" boolean DEFAULT false,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event_participant" (
	"id" serial PRIMARY KEY NOT NULL,
	"eventId" integer,
	"participantId" varchar(256) NOT NULL,
	"status" varchar(32) DEFAULT 'REGISTERED' NOT NULL,
	"poapClaimed" boolean DEFAULT false,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"type" "event_type",
	"status" "event_status" DEFAULT 'DRAFT' NOT NULL,
	"creatorId" varchar(256) NOT NULL,
	"location" varchar(256),
	"startDate" timestamp with time zone NOT NULL,
	"endDate" timestamp with time zone,
	"maxParticipants" integer,
	"poapEventId" varchar(256),
	"imageUrl" varchar(512),
	"actionType" "action_type",
	"actionGoal" integer,
	"actionProgress" integer DEFAULT 0,
	"actionMetadata" jsonb,
	"evidenceRequired" boolean DEFAULT true,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "forum_response" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forum_response_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"forumId" integer,
	"content" text NOT NULL,
	"responderId" varchar(256) NOT NULL,
	"upvotes" integer DEFAULT 0,
	"downvotes" integer DEFAULT 0,
	"parentId" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "forum" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forum_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer,
	"title" varchar(256) NOT NULL,
	"question" text NOT NULL,
	"creatorId" varchar(256) NOT NULL,
	"status" "forum_status" DEFAULT 'OPEN' NOT NULL,
	"upvotes" integer DEFAULT 0,
	"downvotes" integer DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "reward" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reward_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer,
	"type" varchar(32) NOT NULL,
	"tokenAddress" varchar(256),
	"amount" numeric,
	"metadata" jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DROP TABLE "gonzaapp_event_participant" CASCADE;--> statement-breakpoint
DROP TABLE "gonzaapp_event" CASCADE;--> statement-breakpoint
DROP TABLE "gonzaapp_forum_response" CASCADE;--> statement-breakpoint
DROP TABLE "gonzaapp_forum" CASCADE;--> statement-breakpoint
DROP TABLE "gonzaapp_reward" CASCADE;--> statement-breakpoint
ALTER TABLE "event_evidence" ADD CONSTRAINT "event_evidence_eventId_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_participant" ADD CONSTRAINT "event_participant_eventId_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_response" ADD CONSTRAINT "forum_response_forumId_forum_id_fk" FOREIGN KEY ("forumId") REFERENCES "public"."forum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_response" ADD CONSTRAINT "forum_response_parentId_forum_response_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."forum_response"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum" ADD CONSTRAINT "forum_eventId_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reward" ADD CONSTRAINT "reward_eventId_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "evidence_event_idx" ON "event_evidence" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "evidence_participant_idx" ON "event_evidence" USING btree ("participantId");--> statement-breakpoint
CREATE INDEX "participant_event_idx" ON "event_participant" USING btree ("eventId","participantId");--> statement-breakpoint
CREATE INDEX "event_creator_idx" ON "event" USING btree ("creatorId");--> statement-breakpoint
CREATE INDEX "event_type_idx" ON "event" USING btree ("type");--> statement-breakpoint
CREATE INDEX "event_status_idx" ON "event" USING btree ("status");--> statement-breakpoint
CREATE INDEX "event_action_type_idx" ON "event" USING btree ("actionType");--> statement-breakpoint
CREATE INDEX "response_forum_idx" ON "forum_response" USING btree ("forumId");--> statement-breakpoint
CREATE INDEX "response_responder_idx" ON "forum_response" USING btree ("responderId");--> statement-breakpoint
CREATE INDEX "response_parent_idx" ON "forum_response" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "forum_event_idx" ON "forum" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "forum_creator_idx" ON "forum" USING btree ("creatorId");--> statement-breakpoint
CREATE INDEX "forum_status_idx" ON "forum" USING btree ("status");--> statement-breakpoint
CREATE INDEX "reward_event_idx" ON "reward" USING btree ("eventId");