CREATE TABLE "event_vote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer,
	"voterId" varchar(256) NOT NULL,
	"voteType" boolean NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "event_vote" ADD CONSTRAINT "event_vote_eventId_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "vote_event_idx" ON "event_vote" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "vote_voter_idx" ON "event_vote" USING btree ("voterId");--> statement-breakpoint
CREATE UNIQUE INDEX "vote_unique_idx" ON "event_vote" USING btree ("eventId","voterId");