import { Geist, Geist_Mono } from 'next/font/google';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import {
  FaLeaf,
  FaGift,
  FaBell,
  FaSignInAlt,
  FaUserPlus,
} from 'react-icons/fa';
import '~/styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Puedes traer puntos y notificaciones globales aquí si lo necesitas
  // const puntos = ...;
  // const notificaciones = ...;

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex items-center justify-between bg-[#2E7D32] px-4 py-3 text-white shadow-lg md:px-8">
            <div className="flex items-center gap-3">
              <FaLeaf className="text-2xl md:text-3xl" />
              <a
                href="/usuario"
                className="text-xl font-extrabold tracking-tight transition hover:underline md:text-2xl"
              >
                SellGreen
              </a>
            </div>
            <div className="flex items-center gap-2 md:gap-4">
              {/* Puedes pasar puntos y notificaciones como props si lo necesitas */}
              <span className="flex items-center gap-1 rounded-full bg-[#2962FF] px-3 py-1 text-sm text-white shadow md:text-base">
                <FaGift className="text-[#FFD700]" />
                <span className="font-semibold">{/* puntos */}0 pts</span>
              </span>
              <button className="relative rounded-full p-2 transition hover:bg-[#388e3c]">
                <FaBell className="text-lg md:text-xl" />
                {/* <span className="absolute -top-1 -right-1 rounded-full bg-[#EF5350] px-1 text-xs">
                  {notificaciones.length}
                </span> */}
              </button>
              <div className="flex items-center gap-2">
                <SignedIn>
                  <UserButton afterSignOutUrl="/" />
                </SignedIn>
                <SignedOut>
                  <SignInButton mode="modal">
                    <button className="text-primary-green border-primary-green hover:bg-primary-green flex items-center gap-2 rounded border bg-white px-4 py-2 font-semibold transition hover:text-white">
                      <FaSignInAlt /> Iniciar sesión
                    </button>
                  </SignInButton>
                  <SignUpButton mode="modal">
                    <button className="bg-secondary-yellow border-secondary-yellow flex items-center gap-2 rounded border px-4 py-2 font-semibold text-black transition hover:bg-yellow-300">
                      <FaUserPlus /> Registrarse
                    </button>
                  </SignUpButton>
                </SignedOut>
              </div>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
