CREATE TABLE IF NOT EXISTS gonzaapp_user_points (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  puntos INTEGER NOT NULL,
  descripcion VARCHAR(256),
  fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gonzaapp_users (
  id VARCHAR(128) PRIMARY KEY,
  email VARCHAR(256) NOT NULL,
  name VARCHAR(256),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gonzaapp_user_history (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  action VARCHAR(256) NOT NULL,
  points INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
